fragment HomeParts on Home {
  __typename
  hero {
    __typename
    title
    description
    primaryButtonText
    secondaryButtonText
  }
  about {
    __typename
    label
    heading
    intro
    description
    timeline {
      __typename
      year
      title
      institution
      courses
    }
  }
  services {
    __typename
    label
    description
    highlight
    cardTitle
    cardDescription
    buttonText
    items
  }
  contacts {
    __typename
    label
    description
    phoneLabel
    phoneValue
    hoursLabel
    hoursValue
    hoursSubValue
  }
}
